import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import "reactflow/dist/style.css";
import AuthSession from "./AuthSession";

const vazirmatn = Vazirmatn({ subsets: ["arabic","latin","latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
      <body className={vazirmatn.className}>
        <AuthSession>{children}</AuthSession>
      </body>
    </html>
  );
}
